import jsPDF from "jspdf";

export const downloadTextAsPdf = (title: string, content: string, filename: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin, 25);

  // Date
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(new Date().toLocaleDateString("en-IN"), margin, 33);
  doc.setTextColor(0);

  // Content
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(content, maxWidth);
  let y = 42;

  for (const line of lines) {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Sarkari Yojana Mitra AI", margin, 290);

  doc.save(filename);
};

export const downloadChecklistAsPdf = (
  schemeName: string,
  docs: string[],
  checked: Record<string, boolean>
) => {
  const pdf = new jsPDF();
  const margin = 20;

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(`Document Checklist`, margin, 25);

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text(schemeName, margin, 34);

  pdf.setFontSize(9);
  pdf.setTextColor(120);
  pdf.text(new Date().toLocaleDateString("en-IN"), margin, 41);
  pdf.setTextColor(0);

  let y = 52;
  pdf.setFontSize(11);
  docs.forEach((doc, i) => {
    const isChecked = checked[doc];
    const prefix = isChecked ? "[x]" : "[ ]";
    pdf.text(`${prefix}  ${doc}`, margin, y);
    y += 8;
    if (y > 275) {
      pdf.addPage();
      y = 20;
    }
  });

  const checkedCount = docs.filter((d) => checked[d]).length;
  y += 5;
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  pdf.text(`Progress: ${checkedCount}/${docs.length}`, margin, y);

  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text("Generated by Sarkari Yojana Mitra AI", margin, 290);

  pdf.save(`checklist-${schemeName.replace(/\s+/g, "-").toLowerCase()}.pdf`);
};
